import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-anecdotes',
  templateUrl: 'anecdotes.html',
})
export class AnecdotesPage {
  list: any;

  constructor(public navCtrl: NavController, public navParams: NavParams) {
  	this.list = [
  		{ "anecdote" : "Je me suis planté une fourchette dans l’aisselle",
  	  	  "number" : "1"},
  		{ "anecdote" : "J’ai failli devenir aveugle en faisant la vaisselle",
  	  	  "number" : "2"},
  		{ "anecdote" : "J’ai été soliste dans une chorale",
  	  	  "number" : "3"},
  		{ "anecdote" : "Quand je portais encore des couches, j’ai mangé des croquettes pour chien",
  	  	  "number" : "4"},
  		{ "anecdote" : "Je me suis fait virer des enfants de cœur quand j'étais petit",
  	  	  "number" : "5"},
  		{ "anecdote" : "Mon grand-père était premier ministre",
  	  	  "number" : "6"},
  		{ "anecdote" : "J'ai peur des oies",
  	  	  "number" : "7"},
  		{ "anecdote" : "Enfant, je me suis approché du bassin d'une piscine remplie de personnes et j'ai intentionnellement fait pipi dedans",
  	  	  "number" : "8"},
  		{ "anecdote" : "Lors de mon stage ouvrier, personne n'arrivait à dire mon prénom, on m'a donc appelé Michel pendant 1 mois",
  	  	  "number" : "9"},
  		{ "anecdote" : "J'ai failli être mariée à un berbère en échange de chèvres",
  	  	  "number" : "10"},
  		{ "anecdote" : "Je me suis prise 2 vitres à la suite",
  	  	  "number" : "11"},
  		{ "anecdote" : "Je me suis cassé la clavicule en rentrant dans une porte",
  	  	  "number" : "12"},
  		{ "anecdote" : "J'ai fait tomber mon portable 2 fois dans les toilettes en une semaine",
  	  	  "number" : "13"},
  		{ "anecdote" : "Quand j'étais bébé j'ai rebondit sur la table à langer, le lavabo, la baignoire et le sol",
  	  	  "number" : "14"},
  		{ "anecdote" : "Je sais mettre mes 2 pieds derrière la tête",
  	  	  "number" : "15"},
  		{ "anecdote" : "Je n'ai qu'un seul rein",
  	  	  "number" : "16"},
  		{ "anecdote" : "J'ai été vice-champion de France de football américain",
  	  	  "number" : "17"},
  		{ "anecdote" : "Suite à un pari perdu en étant alcoolisé, j'ai fait la grosse comission devant un hopital",
  	  	  "number" : "18"},
  		{ "anecdote" : "Je me suis ouvert le crâne en faisant une mayonnaise",
  	  	  "number" : "19"},
  		{ "anecdote" : "J'ai perdu le permis pour alcoolémie au bout de 3 mois",
  	  	  "number" : "20"},
  		{ "anecdote" : "Je regarde Plus belle la vie depuis le CP",
  	  	  "number" : "21"},
  		{ "anecdote" : "Je suis breton",
  	  	  "number" : "22"},
  		{ "anecdote" : "J'ai traversé plus de 10 pays en 6 mois",
  	  	  "number" : "23"},
  		{ "anecdote" : "J'ai passé une soirée bloqué dans l'ascenceur de St-Omer et bourré car mon accolyte sautait dedans, j'ai vomi en sortant",
  	  	  "number" : "24"},
  		{ "anecdote" : "J'ai mis mon nez dans les fesses de Julien Mathieu",
  	  	  "number" : "25"},
  		{ "anecdote" : "J'ai tué les poissons rouges de ma classe de maternelle",
  	  	  "number" : "26"},
  		{ "anecdote" : "Mes parents m'ont perdue dans une station service quand j'avais 3 ans car j'étais aux toilettes pour hommes",
  	  	  "number" : "27"},
  		{ "anecdote" : "Je connais toutes les chansons de colonel Reyel par cœur",
  	  	  "number" : "28"},
  		{ "anecdote" : "Quand je suis né, j'avais les testicules bleues... heureusement ce n'est plus le cas maintenant",
  	  	  "number" : "29"},
  		{ "anecdote" : "J'ai peur des insectes volants",
  	  	  "number" : "30"},
  		{ "anecdote" : "Enfant, je voulais devenir clown",
  	  	  "number" : "31"},
  		{ "anecdote" : "Je suis restée coincée sur un toît pendant 1h et, alors que je voulais descendre, mon frère m'envoyait des ballons",
  	  	  "number" : "32"},
  		{ "anecdote" : "Suite à un accident de voiture (je me suis pris des poteaux en faisant coucou à un pote), je suis arrivée en retard en cours. Le prof en a bien ri lorsqu'il a écrit \"le jury de fin d'année est plus attentif que les examinateurs du permis\" à côté de mon 5/20.",
  	  	  "number" : "33"},
  		{ "anecdote" : "A 2 ans, j'adorais les huitres",
  	  	  "number" : "34"},
  		{ "anecdote" : "J'ai voulu faire peur à ma grand-mère en feintant un tir avec un pistolet à bille, le seul problème c'est qu'il était bel et bien chargé --> headshot j'ai pris très cher",
  	  	  "number" : "35"},
  		{ "anecdote" : "J'ai déjà echangé de classe avec mon frère sans que personne ne s'en rende compte",
  	  	  "number" : "36"},
  		{ "anecdote" : "J'ai peur des crottes de nez",
  	  	  "number" : "37"},
  		{ "anecdote" : "Avec 3 sœurs et aucun frère, j'ai dû jouer à papa et maman or je préférai encore jouer le chien que le père… bilan 2 mamans lesbiennes, une fille et un chien…",
  	  	  "number" : "38"},
  		{ "anecdote" : "Alors que j'étais perdu, j'ai toqué et dormi chez des inconnus",
  	  	  "number" : "39"},
  		{ "anecdote" : "Après une soirée arrosée, je me suis endormi pendant l'acte",
  	  	  "number" : "40"},
  	]
  }

}
